from ui import print, input
from combat import simple_combat
from enemy import Consequential, MotherRaven, Dara


def _print_creature_duo(player):
  print("\nThe torchlight gives life to its features.")
  print("\nBlack fur bristling through shredded clothing.")
  print("Legs that belong to something arachnid —")
  print("except one, which is human, joined up")
  print("at the hip — kicking out at what isn't")
  print("attacking it.")
  print("Or maybe fighting the fact")
  print("that this is its existence.")
  print("\nAn arm that once was human,")
  print("and now appears to be a crab's pincer.")
  print("\nAnd a face —")
  print("what's left of one —")
  print("three eyes crowded together on its edge,")
  print("with a mouth full of sharp, glistening things")
  print("inside, stretched up toward its ears")
  print("on the left side.")


def duo_dungeon_route(player):
  player.flags['ch1_branch_complete'] = True

  print("\n\nThe corridor splits.")
  print("\nLeft — a ladder bolted to the wall.")
  print("Above it, the sound of wings.")
  print("\nRight — the corridor continues.")
  print("Longer. Darker.")
  print("\nMira doesn't ask. She's already moving right.")

  print("\nYou start walking forward.")
  print("Caleb ahead, half-turned — watching the way")
  print("you came the whole time.")
  print("Mira behind you.")
  print("\nThen — a door on the left.")
  print("A sound from behind it.")
  print("Soft. Rhythmic.")
  print("Someone sobbing.")
  print("Long past the point where sobbing helps.")
  print("\nMira stops.")
  print("\n'We can't just leave them.'")
  print("\nCaleb doesn't stop.")
  print("'We can. We have to.")
  print("Every door we open is time Sera")
  print("doesn't have.'")
  print("\n'You sounded just like them right now.")
  print("Do you hear yourself?'")
  print("\n'I sounded like someone who's trying")
  print("to not waste time on a goal")
  print("that's not our goal!'")
  print("His voice raises slightly in anger.")
  print("'I sound like someone who's trying")
  print("to keep us on tra—'")
  print("\nHis words cut off midway as his mouth")
  print("drops open, staring past Mira,")
  print("from the way you all came.")
  print("\nAlmost as if on cue, you and Mira turn")
  print("your heads in the direction —")
  print("as a sound accompanies the movement.")
  print("\n'hrrrnnHahH'")
  _print_creature_duo(player)
  print("\n'RUN!' Caleb shouts — before anyone")
  print("has the chance to investigate.")
  print("\nThey run. He turns in the direction")
  print("of Sera's cell, Mira behind him.")

  print("\n[1] Run with them.")
  print("[2] Stand your ground. Alone.")
  c = input("\n> ").strip()

  if c == "2":
    monster = Consequential()
    simple_combat(player, monster)
    if not player.is_alive():
      return
    player.gain_exp(monster.exp_value)
    print("\nIt dies the way it moved.")
    print("Wrong. In stages.")
    print("The human leg is the last part to stop.")
    print("\nThe corridor is quiet again.")
    print("The sobbing behind the door isn't.")
    print("\nYou follow the way they ran.")
    print("\nYou find the cell by the sound of voices.")
    print("\nInside — Sera, unbound, on her feet.")
    print("Mira's arm still around her like")
    print("it forgot how to be anywhere else.")
    print("Caleb at the desk, going through papers.")
    print("\nWhatever the reunion was,")
    print("you weren't in it.")
    print("\nSera looks up.")
    print("'Your friend,' she says to Mira.")
    print("Then to you: 'They told me")
    print("what you stopped back there.'")
    player.flags['duo_stood_alone'] = True
  else:
    print("\nIt follows.")
    print("You hear it behind you the whole way —")
    print("wrong feet on old stone.")
    print("\nThe cell door is open ahead. You all pour in —")
    print("and it fills the doorframe behind you.")
    monster = Consequential()
    monster.atk = max(1, monster.atk - 2)
    simple_combat(player, monster)
    if not player.is_alive():
      return
    player.gain_exp(monster.exp_value)
    print("\nIt dies the way it moved.")
    print("Wrong. In stages.")
    print("The human leg is the last part to stop.")
    print("\nMira pulls her sister into an embrace —")
    print("long, and lovingly held,")
    print("like she's making up for every day")
    print("of it at once.")

  print("\n'How touching.'")
  print("\nFrom the doorframe.")
  print("\n'Too bad this is where it all ends for you.'")
  print("\nDara — in full regalia, and with a sadistic")
  print("grin on her face as she casually walks")
  print("a few steps into the room.")
  print("\nShe isn't hurrying. Doesn't need to.")
  print("People who hold the only exit don't have to.")
  print("\nShe takes the room in.")
  print("Mira. Caleb. Sera, unbound. And you.")
  print("A calculation happens behind her eyes.")
  print("She starts speaking while looking you")
  print("straight in the eyes.")
  print("\n'Do you know what she's worth?'")
  print("She nods at Sera.")
  print("'They think she's a map to the artifacts.")
  print("Which she is.")
  print("But maps can't always be trusted —")
  print("especially if one doesn't have a legend")
  print("to decipher them.' She sighs.")
  print("'I'd hoped to use torture as a way")
  print("of acting as that legend.'")
  print("\nShe continues on as she shares glances")
  print("with the entire party — her perfectly")
  print("brown hair framing her face, as if even it")
  print("was too scared to move.")
  print("\n'The Twilight believes it's ancient.")
  print("Inevitable. The leadership believes it")
  print("hardest — sitting on something")
  print("they've never seen and don't understand.'")
  print("\n'I understand it. I ALONE can harness it!'")
  print("\n'There's a voice under this world.")
  print("It has more names than the world")
  print("has languages.")
  print("The Twilight Ledger named themselves")
  print("after one of them —")
  print("children naming themselves after a king.'")
  print("\n'I intend to meet the king.'")
  print("\nCaleb, flat:")
  print("'She's confessing.")
  print("People confess when they've decided")
  print("the audience won't repeat it.'")
  print("And slowly adds:")
  print("'Because they won't be able to.'")
  print("\n'He's quick,' Dara says.")
  print("'I can see why they kept you breathing.'")
  print("\nThe knife is in her hand")
  print("before you see her draw it.")

  boss = Dara()
  boss.atk = max(1, boss.atk - 2)
  simple_combat(player, boss)
  if not player.is_alive():
    return
  player.gain_exp(boss.exp_value)
  player.flags['dara_dead'] = True

  print("\nShe goes down the way she did everything.")
  print("Efficiently. No wasted syllables.")
  print("\nAt the end she looks at you.")
  print("Only you.")
  print("\n'Looks like you'll be that legend,' she says.")
  print("\nThen nothing more, as she closes her eyes.")
  print("\nSera breaks the silence that follows.")
  print("\n'More will be coming.")
  print("She didn't walk this deep alone —")
  print("and dead operatives get noticed")
  print("faster than live prisoners.'")
  print("\nNobody argues.")
  print("\nYou all move — back down the corridor,")
  print("toward the way out.")
  print("\nYou almost leave.")
  print("\nThen Caleb stops.")
  print("\n'This is only part of the problem solved.'")
  print("He turns back to face the three of you.")
  print("'The ravens. Something down here")
  print("is sending them. We walk out now,")
  print("and every road we take after this,")
  print("we take being assaulted by their pursuit.'")
  print("\nSera goes still — remembering.")
  print("\n'I saw them. Through the door slot,")
  print("when they moved me. Guards hauling meat —")
  print("raw, buckets of it. Like something")
  print("was being fed.")
  print("Or someone.'")
  print("\nShe points down to the opposite end")
  print("of the corridor.")
  print("\n'A door. With a lone ladder in it.")
  print("That direction.'")
  print("\nThe party moves — checking doors")
  print("quickly along the route to it.")
  print("But each one is either a victim")
  print("long forgotten, or a lone room")
  print("waiting to ensnare its next capture.")

  print("\n\nThe ladder ends at a latch.")
  print("\nYou go first — ease it open")
  print("a finger's width. Peek.")
  print("\nPeeking through the gap —")
  print("\nThe aviary is vast.")
  print("More space than the dungeon below")
  print("should be able to contain.")
  print("\nRavens on every surface. Still.")
  print("\nAnd at the center —")
  print("\nLarger than the rustling of wings")
  print("you thought was just a figment")
  print("of your imagination when you entered")
  print("the dungeon.")
  print("She stands at least ten feet tall.")
  print("Blacker than the nighttime sky")
  print("could ever hope to be.")
  print("\nA smell of dirt, rot, and droppings")
  print("assaults your senses all at the same time.")
  print("\nHer wings are pinned elegantly to her")
  print("as she sits atop a branch extending")
  print("from a manmade post in the middle")
  print("of her roost.")
  print("\nShe doesn't look like what made the others —")
  print("but for sure what they one day")
  print("might become, if lucky.")
  print("\nShe noticed you as soon as you peeked")
  print("into her lair.")
  print("But she took no interest.")
  print("For what threat lay in you?")
  print("\nThe others climb through behind you.")
  print("Still, she doesn't move.")
  print("\nThen Sera pulls herself into the room.")
  print("\nThe one thing she hadn't counted on.")
  print("\nThe head turns.")
  print("Every eye finds the hatch.")
  print("\nShe pauses.")
  print("\nThe entrance of Sera made her give pause —")
  print("maybe doubt crossed her mind,")
  print("maybe recognition from senses.")
  print("The whys will never be known.")
  print("\nBut it gave the party enough time")
  print("to go on the offense.")
  print("\nThen she erupts off the branch.")
  print("\nCaleb takes a talon across the shoulder.")
  print("A wing-buffet slams Mira into the frame.")
  print("The beak finds you before you find")
  print("your footing.")
  player.hp = max(1, player.hp - 8)
  print(f"[-8 HP]  [{player.hp}/{player.max_hp}]")

  mother_raven = MotherRaven()
  mother_raven.atk = max(1, mother_raven.atk - 2)
  simple_combat(player, mother_raven)
  if not player.is_alive():
    return
  player.gain_exp(mother_raven.exp_value)
  player.flags['mother_raven_defeated'] = True

  print("\nThe last spell finds her mid-flight.")
  print("\nShe doesn't go through a wall.")
  print("She doesn't take the room with her.")
  print("\nShe just stops —")
  print("like something enormous being unplugged —")
  print("and slumps.")
  print("\nThe floor takes her weight")
  print("and the whole aviary shudders once.")
  print("\nThen stillness.")
  print("\nThe ravens on every surface go still.")
  print("Then scatter — through gaps you didn't")
  print("see before. Gone.")

  print("\nAmong the feathers on the floor —")
  print("one that's different from the others.")
  print("Longer. Darker.")
  print("It doesn't move when the others scatter.")
  print("\nYou take it.")
  print("Raven Talon acquired.")
  player.inventory.add("Raven Talon")

  print("\nSera steps around the body.")
  print("\n'Now you know what I know.")
  print("East. Past the ruins. Into the desert.")
  print("Five artifacts. Together they find it —")
  print("the Ledger. The real one.")
  print("The thing these imitators named")
  print("themselves after.")
  print("\nGet to them first.")
  print("Because you've seen tonight what")
  print("the people who want them are willing")
  print("to do to a stranger.")
  print("Imagine what they'd do with a god.'")
  player.flags['artifact_rumor_east'] = True
  player.flags['sera_freed'] = True

  print("\nCaleb points — up, across the aviary.")
  print("\nAn opening. Top of the far wall,")
  print("where the roof stopped agreeing")
  print("with the architecture.")
  print("Night air moving through it.")
  print("\nYou climb to it. Look down.")
  print("\nBelow, piled against the facility wall —")
  print("hay.")

  print("\n[1] Take the fall.")
  print("[2] Look for another way down.")
  cf = input("\n> ").strip()

  if cf == "1":
    print("\nYou jump.")
    print("The hay does most of the catching.")
    print("The ground does the rest.")
    player.hp = max(1, player.hp - int(player.max_hp * 0.25))
    print(f"[-25% HP]  [{player.hp}/{player.max_hp}]")
  else:
    print("\nYou work your way down — ledge, seam,")
    print("drainpipe, prayer.")
    print("It mostly works.")
    player.hp = max(1, player.hp - int(player.max_hp * 0.10))
    print(f"[-10% HP]  [{player.hp}/{player.max_hp}]")

  print("\nThe night receives you at the bottom.")
  print("The other three come down after —")
  print("slower, smarter, together.")
  print("\nSera looks back at the facility once.")
  print("\n'We're staying. All three of us.")
  print("There's a resistance in this town —")
  print("it just doesn't know it yet.")
  print("We're going to introduce it to itself,")
  print("and take this town back.'")
  print("\nMira takes your hand. Just for a moment.")
  print("Caleb nods once — the whole speech")
  print("he's capable of.")
  print("\nIt isn't your goal to stay")
  print("and play freedom fighter.")
  print("\nEast is.")
  print("\nSo off you go.")
  print("\n              [ CHAPTER 1 ENDS — DUO PATH ]")